# Generated by Django 5.1.6 on 2025-08-19 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('regional', models.CharField(max_length=100)),
                ('codigo_centro', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'CEDULA DE CUIDADANIA'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Certificado de Extranjeria')], max_length=50)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('ficha', models.CharField(max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjeria')], max_length=50)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.CharField(max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_programa', models.CharField(max_length=50, unique=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sst.centroformacion')),
            ],
        ),
        migrations.CreateModel(
            name='InspeccionesSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('epp_correcto', models.BooleanField(default=False)),
                ('herramientas_adecuadas', models.BooleanField(default=False)),
                ('ventilacion_verificada', models.BooleanField(default=False)),
                ('senalizacion_visible', models.BooleanField(default=False)),
                ('area_ordenada', models.BooleanField(default=False)),
                ('equipos_apagados', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('programa_formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sst.programaformacion')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenteSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('ACC', 'Accidente'), ('INC', 'Incidente'), ('NOV', 'Novedad'), ('OBS', 'Observacion')], default='OBS', max_length=3)),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Critico')], max_length=10)),
                ('medidas_tomadas', models.TextField(blank=True)),
                ('aprendiz_involucrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sst.aprendiz')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('programa_formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sst.programaformacion')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('POL', 'Politica de SST'), ('PRO', 'Procedimiento'), ('INS', 'Instructivo'), ('FOR', 'Formato'), ('PLA', 'Plan de Emergencia'), ('REG', 'Reglamento de Higiene y Seguridad')], max_length=3)),
                ('archivo', models.FileField(upload_to='documentos_sst/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('es_general', models.BooleanField(default=True)),
                ('programa_formacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sst.programaformacion')),
            ],
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='programa_formacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sst.programaformacion'),
        ),
    ]
