# Generated by Django 5.2.5 on 2025-08-19 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_alter_aprendiz_options_aprendizcurso_curso_and_more'),
        ('instructores', '0001_initial'),
        ('programas', '0002_alter_programa_perfil_egreso'),
        ('sst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentesst',
            name='aprendiz_involucrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aprendices.aprendiz'),
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='programaformacion',
            name='centro',
        ),
        migrations.AlterField(
            model_name='documentosst',
            name='programa_formacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programas.programa'),
        ),
        migrations.AlterField(
            model_name='inspeccionessst',
            name='programa_formacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.programa'),
        ),
        migrations.AlterField(
            model_name='incidentesst',
            name='programa_formacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.programa'),
        ),
        migrations.RenameField(
            model_name='inspeccionessst',
            old_name='epp_correcto',
            new_name='epp_correcta',
        ),
        migrations.AddField(
            model_name='incidentesst',
            name='instructor_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructores.instructor'),
        ),
        migrations.DeleteModel(
            name='Aprendiz',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='ProgramaFormacion',
        ),
    ]
