# Generated by Django 5.2.4 on 2025-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='perfil_egreso',
            field=models.TextField(verbose_name='Perfil de Egreso'),
        ),
    ]
